[package]
name = "learning"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"
lto = "fat"
strip = true
debug = false
opt-level = "z"
codegen-units = 1

[dependencies]
libc = { version = "0.2", default-features = false }